//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HClinic.Assets.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Default {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Default() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HClinic.Assets.Languages.Default", typeof(Default).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string btnAddName {
            get {
                return ResourceManager.GetString("btnAddName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Doctor.
        /// </summary>
        public static string btnAssistantDoctorName {
            get {
                return ResourceManager.GetString("btnAssistantDoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients Maneger.
        /// </summary>
        public static string btnClientsManagerName {
            get {
                return ResourceManager.GetString("btnClientsManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string btnClientsName {
            get {
                return ResourceManager.GetString("btnClientsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string btnDoctorName {
            get {
                return ResourceManager.GetString("btnDoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string btnDocumentsName {
            get {
                return ResourceManager.GetString("btnDocumentsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string btnDocumentsTitle {
            get {
                return ResourceManager.GetString("btnDocumentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string btnHomeName {
            get {
                return ResourceManager.GetString("btnHomeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID.
        /// </summary>
        public static string btnIdentifyClientTitle {
            get {
                return ResourceManager.GetString("btnIdentifyClientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Card Number.
        /// </summary>
        public static string btnIdentifySessionCardNumberTitle {
            get {
                return ResourceManager.GetString("btnIdentifySessionCardNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string btnIdentifyTitle {
            get {
                return ResourceManager.GetString("btnIdentifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string btnPrintName {
            get {
                return ResourceManager.GetString("btnPrintName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string btnRemoveName {
            get {
                return ResourceManager.GetString("btnRemoveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string btnSearchName {
            get {
                return ResourceManager.GetString("btnSearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Session.
        /// </summary>
        public static string btnSessionNewTitle {
            get {
                return ResourceManager.GetString("btnSessionNewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string btnSettingsName {
            get {
                return ResourceManager.GetString("btnSettingsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string btnUpdateName {
            get {
                return ResourceManager.GetString("btnUpdateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        public static string ClientsDatesName {
            get {
                return ResourceManager.GetString("ClientsDatesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string ClientsSessionsName {
            get {
                return ResourceManager.GetString("ClientsSessionsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heater Printer.
        /// </summary>
        public static string cmbHeaterPrinterTitle {
            get {
                return ResourceManager.GetString("cmbHeaterPrinterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string cmbLanguageTitle {
            get {
                return ResourceManager.GetString("cmbLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Printer.
        /// </summary>
        public static string cmbLaserPrinterTitle {
            get {
                return ResourceManager.GetString("cmbLaserPrinterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string dateFromName {
            get {
                return ResourceManager.GetString("dateFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string dateToName {
            get {
                return ResourceManager.GetString("dateToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with GSM.
        /// </summary>
        public static string errorGsm {
            get {
                return ResourceManager.GetString("errorGsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string FlowDirection {
            get {
                return ResourceManager.GetString("FlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Date.
        /// </summary>
        public static string lblAddDate {
            get {
                return ResourceManager.GetString("lblAddDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string lblApplyTitle {
            get {
                return ResourceManager.GetString("lblApplyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string lblBirthday {
            get {
                return ResourceManager.GetString("lblBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Client.
        /// </summary>
        public static string lblClientAddTitle {
            get {
                return ResourceManager.GetString("lblClientAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string lblClientBirthdayTitle {
            get {
                return ResourceManager.GetString("lblClientBirthdayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string lblClientGenderTitle {
            get {
                return ResourceManager.GetString("lblClientGenderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        public static string lblClientName {
            get {
                return ResourceManager.GetString("lblClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        public static string lblClientNameTitle {
            get {
                return ResourceManager.GetString("lblClientNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string lblClientPhone {
            get {
                return ResourceManager.GetString("lblClientPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string lblClientPhoneTitle {
            get {
                return ResourceManager.GetString("lblClientPhoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Session.
        /// </summary>
        public static string lblCurrentSessionTitle {
            get {
                return ResourceManager.GetString("lblCurrentSessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string lblDateCreation {
            get {
                return ResourceManager.GetString("lblDateCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Date Datetime.
        /// </summary>
        public static string lblDateDateTimeTitle {
            get {
                return ResourceManager.GetString("lblDateDateTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Date.
        /// </summary>
        public static string lblDateNextDateTimeTitle {
            get {
                return ResourceManager.GetString("lblDateNextDateTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datetime.
        /// </summary>
        public static string lblDatetime {
            get {
                return ResourceManager.GetString("lblDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Description.
        /// </summary>
        public static string lblDoctorDescription {
            get {
                return ResourceManager.GetString("lblDoctorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Name.
        /// </summary>
        public static string lblDoctorName {
            get {
                return ResourceManager.GetString("lblDoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} client(s) has received message to remember them his session date tomorrow.
        /// </summary>
        public static string lblDoneSentToAll {
            get {
                return ResourceManager.GetString("lblDoneSentToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave it empty to mean all.
        /// </summary>
        public static string lblEmptyMeanAll {
            get {
                return ResourceManager.GetString("lblEmptyMeanAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string lblError {
            get {
                return ResourceManager.GetString("lblError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of values was duplicated, try a differnce value.
        /// </summary>
        public static string lblErrorDuplicated {
            get {
                return ResourceManager.GetString("lblErrorDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some values is requires.
        /// </summary>
        public static string lblErrorEmptyRequires {
            get {
                return ResourceManager.GetString("lblErrorEmptyRequires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSM Settings.
        /// </summary>
        public static string lblGSMSettingsTitle {
            get {
                return ResourceManager.GetString("lblGSMSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        public static string lblInfoSettings {
            get {
                return ResourceManager.GetString("lblInfoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string lblIsActive {
            get {
                return ResourceManager.GetString("lblIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string lblJob {
            get {
                return ResourceManager.GetString("lblJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Sessions.
        /// </summary>
        public static string lblLastSessionsTitle {
            get {
                return ResourceManager.GetString("lblLastSessionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Last Date.
        /// </summary>
        public static string lblLastSessionTitle {
            get {
                return ResourceManager.GetString("lblLastSessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Panel.
        /// </summary>
        public static string lblLoginTitle {
            get {
                return ResourceManager.GetString("lblLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic Managment System.
        /// </summary>
        public static string lblMainTitle {
            get {
                return ResourceManager.GetString("lblMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Settings.
        /// </summary>
        public static string lblNetworkSettingsTitle {
            get {
                return ResourceManager.GetString("lblNetworkSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string lblPersonalInformationTitle {
            get {
                return ResourceManager.GetString("lblPersonalInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printers Settings.
        /// </summary>
        public static string lblPrintersSettingsTitle {
            get {
                return ResourceManager.GetString("lblPrintersSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID OR Phone OR Client Name.
        /// </summary>
        public static string lblSearchIn {
            get {
                return ResourceManager.GetString("lblSearchIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP.
        /// </summary>
        public static string lblSessionBloodPressureTitle {
            get {
                return ResourceManager.GetString("lblSessionBloodPressureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Date.
        /// </summary>
        public static string lblSessionDateTitle {
            get {
                return ResourceManager.GetString("lblSessionDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Diabetes.
        /// </summary>
        public static string lblSessionDiabetesTypeTitle {
            get {
                return ResourceManager.GetString("lblSessionDiabetesTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HbAlC.
        /// </summary>
        public static string lblSessionHbAlCTitle {
            get {
                return ResourceManager.GetString("lblSessionHbAlCTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR.
        /// </summary>
        public static string lblSessionHeartBeatTitle {
            get {
                return ResourceManager.GetString("lblSessionHeartBeatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string lblSessionNoteTitle {
            get {
                return ResourceManager.GetString("lblSessionNoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RBS.
        /// </summary>
        public static string lblSessionSugarTitle {
            get {
                return ResourceManager.GetString("lblSessionSugarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        public static string lblSessionTitle {
            get {
                return ResourceManager.GetString("lblSessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string lblSessionWeightTitle {
            get {
                return ResourceManager.GetString("lblSessionWeightTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string lblUsername {
            get {
                return ResourceManager.GetString("lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Reported.
        /// </summary>
        public static string notReported {
            get {
                return ResourceManager.GetString("notReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reported.
        /// </summary>
        public static string reported {
            get {
                return ResourceManager.GetString("reported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string txtClientName {
            get {
                return ResourceManager.GetString("txtClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string txtUserName {
            get {
                return ResourceManager.GetString("txtUserName", resourceCulture);
            }
        }
    }
}
